name: ci
on: [ push, pull_request ]
env:
  X_PYTHON_MIN_VERSION: "3.10"

jobs:
  server-aas-test-engines:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ env.X_PYTHON_MIN_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.X_PYTHON_MIN_VERSION }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install aas-test-engines
      - name: Prepare test data
        run: |
          mkdir -p aas_mapping/test/aas-test-engines/input
          curl -L -o aas_mapping/test/aas-test-engines/input/TestDataWithThumbnail.aasx \
          https://media.githubusercontent.com/media/admin-shell-io/aas-test-engines/main/bin/check_servers/test_data/TestDataWithThumbnail.aasx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker image with cache
        uses: docker/build-push-action@v6
        with:
          context: .
          file: aas_mapping/test/aas-test-engines/Dockerfile
          push: false
          tags: aas-server
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: Run container
        run: |
          docker compose -f aas_mapping/test/aas-test-engines/compose.yml up --build -d
      - name: Check if container is running
        run: |
          docker inspect --format='{{.State.Running}}' aas-server | grep true
      - name: Wait for AAS server to be ready
        run: |
          timeout 30s bash -c '
            until docker logs aas-server 2>&1 | grep -q "* Running on"; do
              sleep 2
            done
          '
      - name: Run AAS Test Engines compliance check
        run: |
          FILTER=$(tr -d '\n' < ./aas_mapping/test/aas_test_engines/aas_test_engines_filter.txt)
          aas_test_engines check_server \
            http://localhost:8080/api/v3.0 \
            https://admin-shell.io/aas/API/3/0/AssetAdministrationShellRepositoryServiceSpecification/SSP-002 \
            --filter "$FILTER" \
            --output html > result.html
      - name: Upload test results as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: aas-test-results
          path: result.html
      - name: Show server logs if test failed
        if: failure()
        run: |
          echo "===== AAS Server Logs ====="
          docker logs aas-server
          echo "===== Neo4j Logs ====="
          docker logs neo4j-db
      - name: Stop and remove the container
        if: always()
        run: |
          docker stop aas-server && docker rm aas-server && docker stop neo4j-db && docker rm neo4j-db